/* tslint:disable */
/* eslint-disable */
/**
 * full-stack-framework API
 * Automatically generated OpenAPI spec from Postman collection \"full-stack-framework\"
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface AddTenantsRequest {
    'tenants': Array<Tenant>;
}
export interface AddTestcasesRequest {
    'testcases': Array<Testcase>;
}
export interface DeleteTenantsRequest {
    'tenants': Array<Tenant>;
}
export interface DeleteTestcasesRequest {
    'testcases': Array<Testcase>;
}
export interface GetGithubPRsResponse {
    'message': string;
    'nfs'?: Array<NfPRs>;
}
export interface GetTenantsResponse {
    'message': string;
    'tenants'?: Array<Tenant>;
}
export interface GetTestcasesResponse {
    'message': string;
    'testcases'?: Array<Testcase>;
}
export interface LoginRequest {
    'username': string;
    'password': string;
}
export interface LoginResponse {
    'message': string;
    'token': string;
}
export interface MessageResponse {
    'message'?: string;
}
export interface NfPRs {
    'name': string;
    'prs'?: Array<PR>;
}
export interface PR {
    'number': number;
    'title': string;
}
export interface Tenant {
    'username': string;
    'role': string;
}
export interface Testcase {
    'name': string;
    'link'?: string;
}

/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add tenants
         * @param {AddTenantsRequest} addTenantsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addTenants: async (addTenantsRequest: AddTenantsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addTenantsRequest' is not null or undefined
            assertParamExists('addTenants', 'addTenantsRequest', addTenantsRequest)
            const localVarPath = `/api/admin/tenant`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addTenantsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Add testcases
         * @param {AddTestcasesRequest} addTestcasesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addTestcases: async (addTestcasesRequest: AddTestcasesRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addTestcasesRequest' is not null or undefined
            assertParamExists('addTestcases', 'addTestcasesRequest', addTestcasesRequest)
            const localVarPath = `/api/admin/test/testcase`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addTestcasesRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete tenants
         * @param {DeleteTenantsRequest} deleteTenantsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTenants: async (deleteTenantsRequest: DeleteTenantsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deleteTenantsRequest' is not null or undefined
            assertParamExists('deleteTenants', 'deleteTenantsRequest', deleteTenantsRequest)
            const localVarPath = `/api/admin/tenant`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deleteTenantsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete testcases
         * @param {DeleteTestcasesRequest} deleteTestcasesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTestcases: async (deleteTestcasesRequest: DeleteTestcasesRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deleteTestcasesRequest' is not null or undefined
            assertParamExists('deleteTestcases', 'deleteTestcasesRequest', deleteTestcasesRequest)
            const localVarPath = `/api/admin/test/testcase`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deleteTestcasesRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Github PRs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGithubPRs: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/github`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get tenants
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTenants: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin/tenant`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get testcases
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTestcases: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/test/testcase`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Login
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (loginRequest: LoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginRequest' is not null or undefined
            assertParamExists('login', 'loginRequest', loginRequest)
            const localVarPath = `/api/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Add tenants
         * @param {AddTenantsRequest} addTenantsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addTenants(addTenantsRequest: AddTenantsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addTenants(addTenantsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.addTenants']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Add testcases
         * @param {AddTestcasesRequest} addTestcasesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addTestcases(addTestcasesRequest: AddTestcasesRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addTestcases(addTestcasesRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.addTestcases']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete tenants
         * @param {DeleteTenantsRequest} deleteTenantsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTenants(deleteTenantsRequest: DeleteTenantsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteTenants(deleteTenantsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteTenants']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete testcases
         * @param {DeleteTestcasesRequest} deleteTestcasesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTestcases(deleteTestcasesRequest: DeleteTestcasesRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteTestcases(deleteTestcasesRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteTestcases']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Github PRs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGithubPRs(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetGithubPRsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getGithubPRs(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getGithubPRs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get tenants
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTenants(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetTenantsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTenants(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getTenants']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get testcases
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTestcases(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetTestcasesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTestcases(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getTestcases']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Login
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoginResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(loginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.login']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logout(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logout(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.logout']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Add tenants
         * @param {AddTenantsRequest} addTenantsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addTenants(addTenantsRequest: AddTenantsRequest, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
            return localVarFp.addTenants(addTenantsRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Add testcases
         * @param {AddTestcasesRequest} addTestcasesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addTestcases(addTestcasesRequest: AddTestcasesRequest, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
            return localVarFp.addTestcases(addTestcasesRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete tenants
         * @param {DeleteTenantsRequest} deleteTenantsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTenants(deleteTenantsRequest: DeleteTenantsRequest, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
            return localVarFp.deleteTenants(deleteTenantsRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete testcases
         * @param {DeleteTestcasesRequest} deleteTestcasesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTestcases(deleteTestcasesRequest: DeleteTestcasesRequest, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
            return localVarFp.deleteTestcases(deleteTestcasesRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Github PRs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGithubPRs(options?: RawAxiosRequestConfig): AxiosPromise<GetGithubPRsResponse> {
            return localVarFp.getGithubPRs(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get tenants
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTenants(options?: RawAxiosRequestConfig): AxiosPromise<GetTenantsResponse> {
            return localVarFp.getTenants(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get testcases
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTestcases(options?: RawAxiosRequestConfig): AxiosPromise<GetTestcasesResponse> {
            return localVarFp.getTestcases(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Login
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<LoginResponse> {
            return localVarFp.login(loginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.logout(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Add tenants
     * @param {AddTenantsRequest} addTenantsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addTenants(addTenantsRequest: AddTenantsRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).addTenants(addTenantsRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Add testcases
     * @param {AddTestcasesRequest} addTestcasesRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addTestcases(addTestcasesRequest: AddTestcasesRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).addTestcases(addTestcasesRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete tenants
     * @param {DeleteTenantsRequest} deleteTenantsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteTenants(deleteTenantsRequest: DeleteTenantsRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteTenants(deleteTenantsRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete testcases
     * @param {DeleteTestcasesRequest} deleteTestcasesRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteTestcases(deleteTestcasesRequest: DeleteTestcasesRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteTestcases(deleteTestcasesRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Github PRs
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getGithubPRs(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getGithubPRs(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get tenants
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTenants(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getTenants(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get testcases
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTestcases(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getTestcases(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Login
     * @param {LoginRequest} loginRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).login(loginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Logout
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public logout(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).logout(options).then((request) => request(this.axios, this.basePath));
    }
}



